/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LabeledData } from './labeled-data';
// May contain unused imports in some cases
// @ts-ignore
import { LabeledImage } from './labeled-image';
// May contain unused imports in some cases
// @ts-ignore
import { LabeledShape } from './labeled-shape';
// May contain unused imports in some cases
// @ts-ignore
import { LabeledTrack } from './labeled-track';

/**
 * @type AnnotationsRead
 * @export
 */
export type AnnotationsRead = File | LabeledData;


