/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { InputTypeEnum } from './input-type-enum';

/**
 * 
 * @export
 * @interface AttributeRequest
 */
export interface AttributeRequest {
    /**
     * 
     * @type {string}
     * @memberof AttributeRequest
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof AttributeRequest
     */
    'mutable': boolean;
    /**
     * 
     * @type {InputTypeEnum}
     * @memberof AttributeRequest
     */
    'input_type': InputTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AttributeRequest
     */
    'default_value'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AttributeRequest
     */
    'values': Array<string>;
}



