/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.31.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EventRequest } from './event-request';

/**
 * 
 * @export
 * @interface ClientEventsRequest
 */
export interface ClientEventsRequest {
    /**
     * 
     * @type {Array<EventRequest>}
     * @memberof ClientEventsRequest
     */
    'events'?: Array<EventRequest>;
    /**
     * 
     * @type {EventRequest}
     * @memberof ClientEventsRequest
     */
    'previous_event'?: EventRequest | null;
    /**
     * 
     * @type {string}
     * @memberof ClientEventsRequest
     */
    'timestamp': string;
}

