/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicUser } from './basic-user';
// May contain unused imports in some cases
// @ts-ignore
import { CredentialsTypeEnum } from './credentials-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import { ProviderTypeEnum } from './provider-type-enum';

/**
 * 
 * @export
 * @interface CloudStorageRead
 */
export interface CloudStorageRead {
    /**
     * 
     * @type {number}
     * @memberof CloudStorageRead
     */
    'id'?: number;
    /**
     * 
     * @type {BasicUser}
     * @memberof CloudStorageRead
     */
    'owner'?: BasicUser | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CloudStorageRead
     */
    'manifests'?: Array<string>;
    /**
     * 
     * @type {ProviderTypeEnum}
     * @memberof CloudStorageRead
     */
    'provider_type': ProviderTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CloudStorageRead
     */
    'resource': string;
    /**
     * 
     * @type {string}
     * @memberof CloudStorageRead
     */
    'display_name': string;
    /**
     * 
     * @type {string}
     * @memberof CloudStorageRead
     */
    'created_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CloudStorageRead
     */
    'updated_date'?: string;
    /**
     * 
     * @type {CredentialsTypeEnum}
     * @memberof CloudStorageRead
     */
    'credentials_type': CredentialsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CloudStorageRead
     */
    'specific_attributes'?: string;
    /**
     * 
     * @type {string}
     * @memberof CloudStorageRead
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof CloudStorageRead
     */
    'organization'?: number | null;
}



