/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.31.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BasicUser } from './basic-user';

/**
 * 
 * @export
 * @interface CommentRead
 */
export interface CommentRead {
    /**
     * 
     * @type {number}
     * @memberof CommentRead
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentRead
     */
    'issue'?: number;
    /**
     * 
     * @type {BasicUser}
     * @memberof CommentRead
     */
    'owner'?: BasicUser | null;
    /**
     * 
     * @type {string}
     * @memberof CommentRead
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentRead
     */
    'created_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentRead
     */
    'updated_date'?: string;
}

