/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.4.9
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentWriteRequest
 */
export interface CommentWriteRequest {
    /**
     * 
     * @type {number}
     * @memberof CommentWriteRequest
     */
    'issue': number;
    /**
     * 
     * @type {string}
     * @memberof CommentWriteRequest
     */
    'message'?: string;
}

