/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.30.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FrameMeta } from './frame-meta';

/**
 * 
 * @export
 * @interface DataMetaRead
 */
export interface DataMetaRead {
    /**
     * 
     * @type {string}
     * @memberof DataMetaRead
     */
    'chunks_updated_date': string;
    /**
     * 
     * @type {number}
     * @memberof DataMetaRead
     */
    'chunk_size'?: number | null;
    /**
     * The number of frames included. Deleted frames do not affect this value. 
     * @type {number}
     * @memberof DataMetaRead
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof DataMetaRead
     */
    'image_quality': number;
    /**
     * 
     * @type {number}
     * @memberof DataMetaRead
     */
    'start_frame'?: number;
    /**
     * 
     * @type {number}
     * @memberof DataMetaRead
     */
    'stop_frame'?: number;
    /**
     * 
     * @type {string}
     * @memberof DataMetaRead
     */
    'frame_filter'?: string;
    /**
     * 
     * @type {Array<FrameMeta>}
     * @memberof DataMetaRead
     */
    'frames': Array<FrameMeta> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof DataMetaRead
     */
    'deleted_frames': Array<number>;
    /**
     * A list of valid frame ids. The None value means all frames are included. 
     * @type {Array<number>}
     * @memberof DataMetaRead
     */
    'included_frames'?: Array<number> | null;
}

