/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.30.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BasicOrganization } from './basic-organization';
// May contain unused imports in some cases
// @ts-ignore
import type { BasicUser } from './basic-user';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleEnum } from './role-enum';

/**
 * 
 * @export
 * @interface InvitationRead
 */
export interface InvitationRead {
    /**
     * 
     * @type {string}
     * @memberof InvitationRead
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvitationRead
     */
    'created_date'?: string;
    /**
     * 
     * @type {BasicUser}
     * @memberof InvitationRead
     */
    'owner': BasicUser | null;
    /**
     * 
     * @type {RoleEnum}
     * @memberof InvitationRead
     */
    'role': RoleEnum;
    /**
     * 
     * @type {BasicUser}
     * @memberof InvitationRead
     */
    'user': BasicUser;
    /**
     * 
     * @type {number}
     * @memberof InvitationRead
     */
    'organization': number;
    /**
     * 
     * @type {boolean}
     * @memberof InvitationRead
     */
    'expired'?: boolean | null;
    /**
     * 
     * @type {BasicOrganization}
     * @memberof InvitationRead
     */
    'organization_info': BasicOrganization;
}



