/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.30.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobValidationLayoutRead
 */
export interface JobValidationLayoutRead {
    /**
     * 
     * @type {number}
     * @memberof JobValidationLayoutRead
     */
    'honeypot_count'?: number;
    /**
     * The list of frame ids for honeypots in the job 
     * @type {Array<number>}
     * @memberof JobValidationLayoutRead
     */
    'honeypot_frames'?: Array<number>;
    /**
     * The list of real (validation) frame ids for honeypots in the job 
     * @type {Array<number>}
     * @memberof JobValidationLayoutRead
     */
    'honeypot_real_frames'?: Array<number>;
}

