/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.9.1
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeVal } from './attribute-val';

/**
 * 
 * @export
 * @interface LabeledImage
 */
export interface LabeledImage {
    /**
     * 
     * @type {number}
     * @memberof LabeledImage
     */
    'id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LabeledImage
     */
    'frame': number;
    /**
     * 
     * @type {number}
     * @memberof LabeledImage
     */
    'label_id': number;
    /**
     * 
     * @type {number}
     * @memberof LabeledImage
     */
    'group'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LabeledImage
     */
    'source'?: string;
    /**
     * 
     * @type {Array<AttributeVal>}
     * @memberof LabeledImage
     */
    'attributes'?: Array<AttributeVal>;
}

