/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.5.2
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicUser } from './basic-user';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 
 * @export
 * @interface MetaUser
 */
export interface MetaUser {
    /**
     * 
     * @type {string}
     * @memberof MetaUser
     */
    'url'?: string;
    /**
     * 
     * @type {number}
     * @memberof MetaUser
     */
    'id'?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof MetaUser
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof MetaUser
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof MetaUser
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof MetaUser
     */
    'email'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MetaUser
     */
    'groups': Array<string>;
    /**
     * Designates whether the user can log into this admin site.
     * @type {boolean}
     * @memberof MetaUser
     */
    'is_staff'?: boolean;
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     * @type {boolean}
     * @memberof MetaUser
     */
    'is_superuser'?: boolean;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     * @type {boolean}
     * @memberof MetaUser
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MetaUser
     */
    'last_login'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetaUser
     */
    'date_joined'?: string;
}

