/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.31.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskRead } from './task-read';

/**
 * 
 * @export
 * @interface PaginatedTaskReadList
 */
export interface PaginatedTaskReadList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTaskReadList
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTaskReadList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTaskReadList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<TaskRead>}
     * @memberof PaginatedTaskReadList
     */
    'results': Array<TaskRead>;
}

