/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.6.1
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { InvitationRead } from './invitation-read';

/**
 * 
 * @export
 * @interface PaginatedInvitationReadList
 */
export interface PaginatedInvitationReadList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedInvitationReadList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInvitationReadList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInvitationReadList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<InvitationRead>}
     * @memberof PaginatedInvitationReadList
     */
    'results'?: Array<InvitationRead>;
}

