/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.9.2
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrganizationRead } from './organization-read';

/**
 * 
 * @export
 * @interface PaginatedOrganizationReadList
 */
export interface PaginatedOrganizationReadList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedOrganizationReadList
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOrganizationReadList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOrganizationReadList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<OrganizationRead>}
     * @memberof PaginatedOrganizationReadList
     */
    'results'?: Array<OrganizationRead>;
}

