/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.6.1
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RoleEnum } from './role-enum';

/**
 * 
 * @export
 * @interface PatchedInvitationWriteRequest
 */
export interface PatchedInvitationWriteRequest {
    /**
     * 
     * @type {RoleEnum}
     * @memberof PatchedInvitationWriteRequest
     */
    'role'?: RoleEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedInvitationWriteRequest
     */
    'email'?: string;
}



