/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.4.9
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LocationEnum } from './location-enum';
// May contain unused imports in some cases
// @ts-ignore
import { StorageRequest } from './storage-request';

/**
 * @type PatchedProjectWriteRequestTargetStorage
 * @export
 */
export type PatchedProjectWriteRequestTargetStorage = StorageRequest;


