/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.5.2
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BasicUser } from './basic-user';
// May contain unused imports in some cases
// @ts-ignore
import { JobStatus } from './job-status';
// May contain unused imports in some cases
// @ts-ignore
import { LabelsSummary } from './labels-summary';
// May contain unused imports in some cases
// @ts-ignore
import { Storage } from './storage';
// May contain unused imports in some cases
// @ts-ignore
import { TasksSummary } from './tasks-summary';

/**
 * 
 * @export
 * @interface ProjectRead
 */
export interface ProjectRead {
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    'url'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectRead
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    'name'?: string;
    /**
     * 
     * @type {BasicUser}
     * @memberof ProjectRead
     */
    'owner'?: BasicUser | null;
    /**
     * 
     * @type {BasicUser}
     * @memberof ProjectRead
     */
    'assignee'?: BasicUser | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectRead
     */
    'guide_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    'bug_tracker'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectRead
     */
    'task_subsets'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    'created_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    'updated_date'?: string;
    /**
     * 
     * @type {JobStatus}
     * @memberof ProjectRead
     */
    'status'?: JobStatus;
    /**
     * 
     * @type {string}
     * @memberof ProjectRead
     */
    'dimension'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectRead
     */
    'organization'?: number | null;
    /**
     * 
     * @type {Storage}
     * @memberof ProjectRead
     */
    'target_storage'?: Storage | null;
    /**
     * 
     * @type {Storage}
     * @memberof ProjectRead
     */
    'source_storage'?: Storage | null;
    /**
     * 
     * @type {TasksSummary}
     * @memberof ProjectRead
     */
    'tasks': TasksSummary;
    /**
     * 
     * @type {LabelsSummary}
     * @memberof ProjectRead
     */
    'labels': LabelsSummary;
}



