/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterSerializerExRequest
 */
export interface RegisterSerializerExRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterSerializerExRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterSerializerExRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterSerializerExRequest
     */
    'password1': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterSerializerExRequest
     */
    'password2': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterSerializerExRequest
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterSerializerExRequest
     */
    'last_name'?: string;
}

