/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.31.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AnnotationFileRequest } from './annotation-file-request';
// May contain unused imports in some cases
// @ts-ignore
import type { LabeledDataRequest } from './labeled-data-request';
// May contain unused imports in some cases
// @ts-ignore
import type { LabeledImageRequest } from './labeled-image-request';
// May contain unused imports in some cases
// @ts-ignore
import type { LabeledShapeRequest } from './labeled-shape-request';
// May contain unused imports in some cases
// @ts-ignore
import type { LabeledTrackRequest } from './labeled-track-request';

/**
 * @type TaskAnnotationsUpdateRequest
 * @export
 */
export type TaskAnnotationsUpdateRequest = AnnotationFileRequest | LabeledDataRequest;


