/* tslint:disable */
/* eslint-disable */
/**
 * CVAT REST API
 * REST API for Computer Vision Annotation Tool (CVAT)
 *
 * The version of the OpenAPI document: 2.31.0
 * Contact: support@cvat.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BinaryOperation } from './binary-operation';

/**
 * 
 * @export
 * @interface Transformation
 */
export interface Transformation {
    /**
     * 
     * @type {string}
     * @memberof Transformation
     */
    'name': string;
    /**
     * 
     * @type {BinaryOperation}
     * @memberof Transformation
     */
    'binary'?: BinaryOperation | null;
}

